from pydantic import BaseModel, Field
from typing import Dict, Any, Optional


class AIRequest(BaseModel):
    prompt: str = Field(..., description="The main text prompt for the LLM.")
    system_prompt: Optional[str] = Field(
        None, description="System instructions to guide LLM behavior."
    )
    temperature: Optional[float] = Field(
        None, description="Sampling temperature (0.0 to 1.0)."
    )
    top_p: Optional[float] = Field(
        None, description="Nucleus sampling probability (0.0 to 1.0)."
    )
    max_tokens: Optional[int] = Field(
        None, description="Maximum number of tokens to generate."
    )
    options: Optional[Dict[str, Any]] = Field(
        None, description="Additional model parameters passed to the LLM."
    )


class AIResponse(BaseModel):
    text: str = Field(..., description="The text generated by the LLM.")
    model: str = Field(..., description="The model name that generated the response.")
    provider: str = Field(..., description="The provider name (e.g., 'ollama').")
    usage: Dict[str, int] = Field(
        default_factory=dict,
        description="Token usage stats (e.g., prompt_tokens, completion_tokens, total_tokens)."
    )
    raw_response: Dict[str, Any] = Field(
        default_factory=dict,
        description="The raw payload returned by the underlying provider client."
    )
    duration_ms: float = Field(..., description="Total execution duration in milliseconds.")
