"""create ai_resume_optimizations table

Revision ID: a8ce5399564d
Revises: fa4ae97f2337
Create Date: 2026-07-01 15:55:56.904563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ce5399564d'
down_revision: Union[str, None] = 'fa4ae97f2337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_resume_optimizations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_result', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimization_result', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_score', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_resume_optimizations_resume_id'), 'ai_resume_optimizations', ['resume_id'], unique=False)
    op.create_index(op.f('ix_ai_resume_optimizations_user_id'), 'ai_resume_optimizations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_resume_optimizations_user_id'), table_name='ai_resume_optimizations')
    op.drop_index(op.f('ix_ai_resume_optimizations_resume_id'), table_name='ai_resume_optimizations')
    op.drop_table('ai_resume_optimizations')
    # ### end Alembic commands ###

