"""create_ai_resume_rewrites_table

Revision ID: fa4ae97f2337
Revises: ef18d731bf02
Create Date: 2026-07-01 15:47:26.840577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa4ae97f2337'
down_revision: Union[str, None] = 'ef18d731bf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_resume_rewrites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('original_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewritten_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewrite_mode', sa.String(length=50), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['ai_resume_rewrites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_resume_rewrites_parent_id'), 'ai_resume_rewrites', ['parent_id'], unique=False)
    op.create_index(op.f('ix_ai_resume_rewrites_resume_id'), 'ai_resume_rewrites', ['resume_id'], unique=False)
    op.create_index(op.f('ix_ai_resume_rewrites_user_id'), 'ai_resume_rewrites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_resume_rewrites_user_id'), table_name='ai_resume_rewrites')
    op.drop_index(op.f('ix_ai_resume_rewrites_resume_id'), table_name='ai_resume_rewrites')
    op.drop_index(op.f('ix_ai_resume_rewrites_parent_id'), table_name='ai_resume_rewrites')
    op.drop_table('ai_resume_rewrites')
    # ### end Alembic commands ###
