# Pydantic schema validation models
from app.schemas.user import (
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
    Token,
    TokenData,
)
from app.schemas.resume import (
    ResumeResponse,
    ResumeListResponse,
    ResumeUploadResponse,
)
from app.schemas.parser import (
    EducationItem,
    ExperienceItem,
    ProjectItem,
    ParsedResumeData,
    ParseResumeResponse,
)
from app.schemas.ats import (
    ATSBreakdown,
    ATSRecommendation,
    ATSScoreResponse,
)
from app.schemas.job_match import (
    JobDescription,
    MatchBreakdown,
    MatchRecommendation,
    JobMatchResponse,
)
from app.schemas.job_gap import (
    SkillGap,
    ExperienceGap,
    EducationGap,
    CertificationGap,
    KeywordGap,
    GapAnalysisResponse,
)
from app.schemas.ai_resume_review import (
    PriorityLevel,
    Recommendation,
    ResumeSectionReview,
    ReviewMetadata,
    ResumeReviewResponse,
    ResumeReviewListResponse,
)
from app.schemas.ai_resume_rewrite import (
    ImprovementCategory,
    SectionDiff,
    ChangeTracking,
    RewriteQualityScore,
    KeywordOptimization,
    RewriteMetadata as RewriteMetadataSchema,
    RewriteSection,
    ResumeRewriteRequest,
    ResumeRewriteSectionRequest,
    ResumeRewriteResponse,
    RewriteHistory,
    ResumeRewriteListResponse,
    UndoResponse,
)
from app.schemas.ai_resume_optimization import (
    ResumeQualityScore,
    MissingSkillDetail,
    ATSOptimizationDetail,
    KeywordAnalysis,
    AchievementOptimizationDetail,
    ResumeCompleteness,
    CareerReadinessDetail,
    CareerReadiness,
    IndustryAlignmentDetail,
    OptimizationRecommendation,
    OptimizationMetadata,
    ResumeOptimizationResponse,
    ResumeOptimizationListResponse,
    ResumeOptimizationRequest,
    ResumeWorkflowRequest,
    ResumeWorkflowResponse,
)

__all__ = [
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserUpdate",
    "Token",
    "TokenData",
    "ResumeResponse",
    "ResumeListResponse",
    "ResumeUploadResponse",
    "EducationItem",
    "ExperienceItem",
    "ProjectItem",
    "ParsedResumeData",
    "ParseResumeResponse",
    "ATSBreakdown",
    "ATSRecommendation",
    "ATSScoreResponse",
    "JobDescription",
    "MatchBreakdown",
    "MatchRecommendation",
    "JobMatchResponse",
    "SkillGap",
    "ExperienceGap",
    "EducationGap",
    "CertificationGap",
    "KeywordGap",
    "GapAnalysisResponse",
    "PriorityLevel",
    "Recommendation",
    "ResumeSectionReview",
    "ReviewMetadata",
    "ResumeReviewResponse",
    "ResumeReviewListResponse",
    "ImprovementCategory",
    "SectionDiff",
    "ChangeTracking",
    "RewriteQualityScore",
    "KeywordOptimization",
    "RewriteMetadataSchema",
    "RewriteSection",
    "ResumeRewriteRequest",
    "ResumeRewriteSectionRequest",
    "ResumeRewriteResponse",
    "RewriteHistory",
    "ResumeRewriteListResponse",
    "UndoResponse",
    "ResumeQualityScore",
    "MissingSkillDetail",
    "ATSOptimizationDetail",
    "KeywordAnalysis",
    "AchievementOptimizationDetail",
    "ResumeCompleteness",
    "CareerReadinessDetail",
    "CareerReadiness",
    "IndustryAlignmentDetail",
    "OptimizationRecommendation",
    "OptimizationMetadata",
    "ResumeOptimizationResponse",
    "ResumeOptimizationListResponse",
    "ResumeOptimizationRequest",
    "ResumeWorkflowRequest",
    "ResumeWorkflowResponse",
]





